2025-05-19 15:20:13,632 - INFO - Removing active script execution started
python: can't open file 'C:\\awsusdmjfsxn01.jnj.com\\eth_get_dev_omp\\OMP_JNJ_MD_OMEGA_LAB\\OMPartners\\development\\dispatcher\x08in\\Automation\rdp_users_pyautogui.py': [Errno 2] No such file or directory
Traceback (most recent call last):
<unknown>:2: SyntaxWarning: invalid escape sequence '\e'
<unknown>:1: SyntaxWarning: invalid escape sequence '\e'
  File "\\awsusdmjfsxn01.jnj.com\eth_get_dev_omp\OMP_JNJ_MD_OMEGA_LAB\OMPartners\development\dispatcher\bin\Automation\PAK_Deployment.py", line 725, in <module>
    remove_active_users()
    ~~~~~~~~~~~~~~~~~~~^^
  File "\\awsusdmjfsxn01.jnj.com\eth_get_dev_omp\OMP_JNJ_MD_OMEGA_LAB\OMPartners\development\dispatcher\bin\Automation\PAK_Deployment.py", line 160, in remove_active_users
    subprocess.run(["python", "\\awsusdmjfsxn01.jnj.com\eth_get_dev_omp\OMP_JNJ_MD_OMEGA_LAB\OMPartners\development\dispatcher\bin\Automation\rdp_users_pyautogui.py"], check=True)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SA-ITS-APSOMINT-LAB\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python', '\\awsusdmjfsxn01.jnj.com\\eth_get_dev_omp\\OMP_JNJ_MD_OMEGA_LAB\\OMPartners\\development\\dispatcher\x08in\\Automation\rdp_users_pyautogui.py']' returned non-zero exit status 2.
